spring.application.name=bff-agendador-tarefas

usuario.url=localhost:8081/usuario
agendador-tarefas.url=localhost:8082/tarefas
notificacao.url=localhost:8084/email
server.port=8090

cron.horario=0 0/5 * * * ?

usuario.email=michaeljackson@gmail.com
usuario.senha=12345Michael
jwt.secret=Zm9vYmFyYmF6cXV4cXV1eG9yZ3JhaWxzaXRhbG8yMDI2Zml0ZWM=